### PR TITLE
GHC 7.10 support

### PR DESCRIPTION
**Pull request by phile314**
PR tested with GHC 7.8 and 7.10. Contains the following things:
- Small fix for GHC 7.10 support
- Eliminates warnings in GHC 7.10 (tabs, explicit foralls)

### CODE REVIEW

**Comment by peti** [comment]
Ping?

Is there any particular reason why this PR isn't merged yet?

**Comment by atzedijkstra** [comment]
Is merged, and on hackage, should be ok now. Was delayed because I have currently a broken collarbone.

Atze

> On  28 Apr, 2015, at 13:38 , Peter Simons <notifications@github.com> wrote:
> 
> Ping?
> 
> Is there any particular reason why this PR isn't merged yet?
> 
> —
> Reply to this email directly or view it on GitHub.
> 


                - Atze -

Atze Dijkstra, Department of Information and Computing Sciences. /|\
Utrecht University, PO Box 80089, 3508 TB Utrecht, Netherlands. / | \
Tel.: +31-30-2534118/1454 | WWW  : http://www.cs.uu.nl/~atze . /--|  \
Fax : +31-30-2513971 .... | Email: atze@uu.nl ............... /   |___\

**Comment by peti** [comment]
I applied that patch and tried to use the resulting binary to compile UHC, but the build failed:

    shuffle: src/UHC/Shuffle/Common.hs:(347,1)-(348,35): Non-exhaustive patterns in function variantOfferRef
    src/ehc/files1.mk:437: recipe for target 'build/101/lib-ehc/UHC/Compiler/Base/TermLike.hs' failed

The complete log is at http://hydra.cryp.to/build/787325/nixlog/3/raw.

**Comment by peti** [comment]
@atzedijkstra, oh, I am sorry to hear that you're ill. Get better soon! And thanks for the new release. I'll try to build UHC with the new version ASAP.

**Comment by phile314** [comment]
Thank you Atze for the release. Get better soon.

@peti I plan to take a look at the UHC problems tomorrow.

**Comment by peti** [comment]
OK. thanks everyone for your help!

**Pull request merged**
